"""add favorites many-to-many relationship

Revision ID: 446baa389fdd
Revises: 8ec8162ebeb4
Create Date: 2020-12-15 18:12:22.615672

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '446baa389fdd'
down_revision = '8ec8162ebeb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fav_posts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ondelete='cascade'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name='favorites_pk')
    )
    op.create_index('fav_posts_idx_post', 'fav_posts', ['post_id'], unique=False)
    op.create_index('fav_posts_idx_user', 'fav_posts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('fav_posts_idx_user', table_name='fav_posts')
    op.drop_index('fav_posts_idx_post', table_name='fav_posts')
    op.drop_table('fav_posts')
    # ### end Alembic commands ###
